task: detect  # YOLO task, i.e. detect, segment, classify, pose
mode: train  # YOLO mode, i.e. train, val, predict, export, track, benchmark

# Train settings -------------------------------------------------------------------------------------------------------
model:  yolov8n.pt # path to model file, i.e. yolov8n.pt, yolov8n.yaml
patience: 50
project: cat_dog
name: 8n_640

hsv_h: 0 # 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0 # 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0 # 0.4  # image HSV-Value augmentation (fraction)
degrees: 0 # 0.0  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.1 # 0.5  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0 # 0.0  # image flip up-down (probability)
fliplr: 0.5 # 0.5  # image flip left-right (probability)
mosaic: 0 # 1.0  # image mosaic (probability)
mixup: 0  # image mixup (probability)